### PR TITLE
Remove overly strict and unneeded type restrictions. Fixes #164

### LINKED ISSUE #164: Unnecessary required protocol?
Commit 229d2fa added `<EKManagedMappingProtocol>` to the object parameter and the return type of `+fillObject:fromExternalRepresentation:withMapping:inManagedObjectContext:` (and a few others). However I don't see that `+objectMapping` is actually called on the `objectClass`. This becomes an issue (Xcode warning) if the object being filled does not conform to `EKManagedMappingProtocol` because the same object is filled from two different sources with two different mappings and therefore can't implement `+objectMapping` in a meaningful way.

Is there a place I'm currently missing where the protocol conformance is required? If not, would you be willing to review, discuss and accept a PR changing the fact?

### PR DESCRIPTION
**Pull request by sebastianludwig**
As discussed in #164 I removed the unneeded `<EK[Managed]MappingProtocol>` type specifications.

### CODE REVIEW

**Comment by sebastianludwig** [comment]
Mmmh, the tests fail, but with errors like

> incorrect argument labels in call (have '_:fromExternalRepresentation:with:in:', expected '_:fromExternalRepresentation:withMapping:inManagedObjectContext:')

I'm not that deep into Swift yet, but I can't see how my changes caused these errors oO Have they?

**Comment by DenHeadless** [comment]
Looking into it. It seems that removal of lightweight generics in this case changed the signatures of several methods. I think using NS_SWIFT_NAME can help maintaining backwards compatibility. I will try to patch signatures now on top of your commit.

**Comment by DenHeadless** [comment]
I pushed a commit that retains backwards compatibility onto master, after CI returns with results I can probably make a release. Meanwhile, can you try using latest code from master and testing it on your codebase to verify everything works as expected?

**Comment by sebastianludwig** [comment]
LGTM 👍 Thanks a lot!

**Comment by DenHeadless** [comment]
I pushed [0.22.0 release](https://github.com/lucasmedeirosleite/EasyMapping/releases/tag/0.22.0) with those changes. Thanks for contributing! 🍺

**Pull request merged**
