### PR TITLE
Split fillObject method in 3 separate methods

### PR DESCRIPTION
**Pull request by jcavar**
With this we are able to fill object properties and cache object and then fill relationships after.

### CODE REVIEW

**Comment by DenHeadless** [comment]
Thanks! I'll look into it when I have time. Looks promising, i think we can also reuse this code somehow for EKMapper as well.

**Comment by jcavar** [comment]
Yes, possibly, I looked into it but couldn't find anything related to caching there so I just left it in this part. Is `EKMapper` taking care of primary keys at all? E.g if try to map array with two same objects

**Comment by DenHeadless** [comment]
No, but it has almost same mechanics to fill properties and relationships, so actually the two things that are different are primary key and NSManagedObjectContext.

The reason i'm bringing this up, is that we might want to support Realm, or pure SQLite databases, or any persistance solution really, and then it would be great to reuse all code to fill properties everywhere. 

I'm not saying this should happen in current PR, it's just my thought process at the moment =)

**Comment by jcavar** [comment]
Yes, I see and it makes sense.

**Comment by jcavar** [comment]
https://github.com/Yalantis/FastEasyMapping/blob/master/FastEasyMapping/Source/Deserializer/FEMDeserializer.m#L114

This is actually solved nicely in FastEasyMapping I think. They have generic deserializer and just forward allocation and caching to underlying store.

**Comment by DenHeadless** [comment]
I've merged this as part of d23635b, thanks a lot for contributing!

**Pull request closed without merging**
