### PR TITLE
Crash

### PR DESCRIPTION
**Pull request by ArtemShvydky**
It's very important fix for used mapping by the properties.

### CODE REVIEW

**Comment by lucasmedeirosleite** [comment]
Could you please add some specs to verify this fix?

**Comment by sebastianludwig** [comment]
Or open an issue in which configuration with which input the crash occurs?

**Comment by ArtemShvydky** [comment]
Look, if you need to mapping object with including objects. for example:
mapPropertiesFromDictionary:@{@"pack_id" : @"pack.identifier"} -> crash
Because in this version used valueForKey, a change it to valueForKeyPath and it isn't crash.

**Comment by sebastianludwig** [comment]
So you've got an object with a property `pack` which is another object with a property `identifier`? I think you're supposed to supply another `EKObjectMapping` to `hasOne:forKeyPath:forProperty:withObjectMapping:`. Or is `pack` itself not unmarshalled? I see why this probably works, just not sure it's the right way to use the lib (still trying to figure it out myself) ;-)

**Comment by DenHeadless** [comment]
I think it's extremely rare case, however fix is really small and harmless for everyone, so i cherrypicked it onto master.

**Pull request closed without merging**
